% $Id$

As      = { '-triu( ones( N ) ) + 2 * diag( ones( N, 1 ) )',
            'triu( 10*rand( N ) - 1 ) - 20 * diag( ones( N, 1 ) )',
            'rand( N )',
            'exp(12*rand(N)-6).*(rand(N)-.5)' % for elements of very different size
          };
    
% generate test matrix type k, size N
k = 4;
N = 6;

disp( sprintf( '\nGenerating %d x %d matrix, type %d: generated by\n %s:\n', N, N, k, As{ k } ) );
A = eval( As{ k } )
