% $Id$


As      = { '-triu( ones( N ) ) + 2 * diag( ones( N, 1 ) )',
            'triu( 10*rand( N ) - 1 ) - 20 * diag( ones( N, 1 ) )',
            'rand( N )',
            'exp(16*rand(N)-20).*(rand(N)-.5)',  % for elements of very different size
            'U* diag(2.^(-1:-1:-N)) *V',         % matrix with very different singular values: 1/2 .. 1/(2^N)
            'repmat( randn(N,1), 1, N ) + 1e-15*rand(N)', % rank 1 matrix with slight disturbance
            'U* ( diag(1e-10*ones(N,1)) + diag(ones(N-1,1),1) ) * U'  % matrix with 1 small eval of alg mult N, geom mult 1
            'U* ( diag(1e+10*ones(N,1)) + diag(ones(N-1,1),1) ) * U'  % matrix with 1 big   eval of alg mult N, geom mult 1
          };
          
% generate test matrix type k, size N
k = 4;
N = 6;

% produce some random orthogonal matrices
[U,X]=qr(rand(N));
[V,X]=qr(rand(N));

disp( sprintf( '\nGenerating %d x %d matrix, type %d: generated by\n %s:\n', N, N, k, As{ k } ) );
A = eval( As{ k } )
